### ISSUE TITLE
Graph naming

### ISSUE THREAD

**Issue by br4sco** [miking-lang/miking#102]
We discussed the naming of graphs.

We have _directed_ graphs:
```
G = (V,E) where E = {(v1,v2) where v1,v2 in V}
```
And _un-directed_ graphs:
```
G = (V,E) where E = {{v1,v2} where v1,v2 in V}
```
Moreover, we have additional special cases, such as _bipartite_ graphs.

In my math textbook (Biggs, Discrete Mathematics), a _graph_ is defined as in the second definition, so to me it's intuitive to have the following naming:
```
graph    -- un-directed graph
digraph  -- directed graph
bigraph  -- bipartite graph
```
Comments and other suggestions are welcome!

**Comment by david-broman** [comment]
Just clarify: I have checked both with Cormen et al 
"Introduction on algorithms" (standard book in algorithms) and with the Grimaldi "Discrete and combinatorial mathematics". They both say the same thing. An undirected graph is represented where edges are tuples (directed) and where edges in undirected graphs are represented with unordered pairs, written {v1,v2}. Hence, I think the definitions are exactly what you wrote above. I think I have also seen the definition with undirected graphs using the double direction somewhere, but I am not sure where, so I think the above definitions are what we should use.

But, what I disagree with is to call an undirected graph a `graph`. This is what I think can be misleading. If we use the general term `graph`, it should include both directed and undirected versions. In both my books, the term `graph` is the general form, and when they talk about directed graphs, the abbreviation `digraph` is used. If it is an undirected graph, the term `undirected graph` is used, not just `graph`. As far as I know, there is no short-hand form for undirected graphs. On wikipedia, they use the therm `graph` for un-directed graphs, but I am not sure that this is the best way to do it. They also say "To avoid ambiguity, this type of object may be called precisely an undirected simple graph." 

What I would like to have (in the end) is one library called basically `graph`, and then we have different specializations of a graph, e.g. `directed`, `undirected` and `bipartite`. I think that such an interface would be clearer in the end. As you have seen, many of the operations are the same, so it feels strange to copy the interface each time we have a specialization of a graph. It would be better to have the specialization as a configuration (a property), then rewriting the whole interface. However, I am not sure how to do this in the best way in Mcore right now. 

For inspiration, it could also be good to look at the Boost library regarding graph representations: https://www.boost.org/doc/libs/1_68_0/libs/graph/doc/table_of_contents.html

**Comment by br4sco** [comment]
> Just clarify, this was not what my text books said. I have checked both with Cormen et al

Ah, I miss-understood you then (edited my post).

**Comment by br4sco** [comment]
I cannot think of a good name for un-directed graphs (`ungraph` doesn't really work ^^). Looking some more in my textbook, they call `{v1,v2}` an _edge_ and `(v1,v2)` an _arc_. We could just have `graph` and then have functions `addEdge`, `countEdges`, etc, and `addArc`, `countArcs`, etc. In fact, there seem to exist what is called a [_mixed graph_ ](https://en.wikipedia.org/wiki/Mixed_graph). Not sure how useful that abstraction is in practice though.

**Comment by david-broman** [comment]
Made an update in my post as well :-)
Yes, that might be an alternative.

**Comment by br4sco** [comment]
We can re-open this at a later point if we want.
