### ISSUE TITLE
readFile bug for single-character files

### ISSUE THREAD

**Issue by aathn** [miking-lang/miking#145]
The `readFile` builtin currently seems to return an empty string for files containing only a single character.

I'm guessing this is a bug in `read_file` from `ustring.ml`, but I wasn't able to find it myself.

**Comment by dlunde** [comment]
Maybe @david-broman can take a look at this?

**Comment by aathn** [comment]
This seems to be working now. Not sure what changed...

**Comment by aathn** [comment]
I just revisited this, and it turns out it is not fixed after all.  I must have made some mistake when writing the previous comment.  I have now tracked down the bug and will make a PR.
