### ISSUE TITLE
Support escaped characters in character literals

### ISSUE THREAD

**Issue by EliasC** [miking-lang/miking#17]
MCore currently supports escaped characters (e.g. `\n` or `\\`) in string literals, but not in character literals:

```
utest '\n' with '\n' in
()
```
> ERROR: Unknown character

You can usually get around this by writing `nth "\n" 0`, but it has made implementing parsers in MCore itself more difficult. It should probably be addressed.

**Comment by johnwikman** [comment]
@EliasC This issue has been fixed in #114

cc @david-broman

**Comment by EliasC** [comment]
@johnwikman Awesome! Thanks!
