### ISSUE TITLE
Inconsistencies between the interpreter and boot

### ISSUE THREAD

**Issue by dlunde** [miking-lang/miking#214]
Current differences between the interpreter and boot (which should be corrected at some point?):
- [ ] Quite a few constants are available in boot but not the interpreter (see the comment by @br4sco below)
- [ ] `TmUtest` is not supported in its complete form in the interpreter (I believe @larshum did the last change in boot?)
- [ ] `not` exists in the interpreter, but not in `boot` (it should be removed in the interpreter)

**Comment by br4sco** [comment]
Intrinsics that exists in both `boot` and the interpreter
- [x] `addi`
- [x] `subi`
- [x] `muli`
- [x] `divi`
- [x] `modi`
- [x] `negi`
- [x] `lti`
- [x] `leqi`
- [x] `gti`
- [x] `geqi`
- [x] `eqi`
- [x] `neqi`
- [x] `slli`
- [x] `srli`
- [x] `srai`
- [ ] `arity`
- [x] `addf`
- [x] `subf`
- [x] `mulf`
- [x] `divf`
- [x] `negf`
- [x] `ltf`
- [x] `leqf`
- [x] `gtf`
- [x] `geqf`
- [x] `eqf`
- [x] `neqf`
- [x] `floorfi`
- [x] `ceilfi`
- [x] `roundfi`
- [x] `int2float`
- [x] `string2float`
- [x] `eqc`
- [x] `char2int`
- [x] `int2char`
- [x] `makeSeq`
- [x] `length`
- [x] `concat`
- [x] `get`
- [x] `set`
- [x] `cons`
- [x] `snoc`
- [x] `splitAt`
- [x] `reverse`
- [x] `print`
- [ ] `dprint`
- [x] `readLine`
- [ ] `readBytesAsString`
- [x] `argv`
- [x] `readFile`
- [x] `writeFile`
- [x] `fileExists`
- [x] `deleteFile`
- [x] `error`
- [x] `exit`
- [x] `eqsym`
- [x] `gensym`
- [x] `sym2hash`
- [x] `randIntU`
- [x] `randSetSeed`
- [x] `wallTimeMs`
- [x] `sleepMs`

**Comment by br4sco** [comment]
`not` exists in the interpreter but not in `boot`, so it should be removed.
