### ISSUE TITLE
Rearranging MExpr implemented in MLang

### ISSUE THREAD

**Issue by david-broman** [miking-lang/miking#32]
I have moved the files and split them into `mexpr/eval.mc`,  `mexpr/ast.mc` , and `mexpr/mexpr.mc` (in the `stdlib`). I have also cleaned up and removed old project files (`preboot`) and tests associated to preboot.

 I would like to do some more rearrangements:

- Move semantic functions `tryMatch` to `eval.mc`. 

- Remove fragments such as `UnitPat` and move the `tryMatch` function to `UnitEval`, and move the `syn Pat`, in this case `UnitPat` to the syntax fragment for unit, in this case fragment `Unit`.

- Rename pattern constructors to `PatUnit`, `PatInt` etc. instead of `UnitPat`. By doing so, we have the same formatting as in the other constructors, such as `TmApp`. This is also how we have done it in the OCaml impl. That is, to always have the kind of constructor as the prefix.

- Following the previous point, I would suggest to change to `TyUnit` from `UnitType` in the same way. Right now, we have a mix.

- Right now we have `FunEval` for ast `Fun`, but `ArithEval` for `Int`. I would suggest that we use the same pattern here, i.e. `IntEval` for `Int`.

- I am also thinking of going back to what we discussed before, i.e., to call the syntax fragments `IntAst` instead of just `Int`. I think it makes even more sense now when we have separated it into a specific file that is called `ast.mc`. 

This RFC is specifically target to @elegios and @EliasC since you have been working on this, but everyone is of course welcome to comment. I would appreciate quick answers, so that I can proceed.

**Comment by elegios** [comment]
Seems reasonable to me.

**Comment by EliasC** [comment]
In general I agree. Some comments:

> Move semantic functions tryMatch to eval.ml.

~Do you mean `mexpr/eval.mc`? Or are you rearranging stuff in the OCaml implementation as well?~
**saw the edit now**

> Move [pattern syntax] to the syntax fragment [...]

I can see a strength in being able to reason about (e.g.) the syntax of integers without automatically introducing integers as patterns. On the one hand, this is what we want for MCore. On the other hand, this prevents reusing that fragment in other languages that might have more limited pattern matching.

> I am also thinking of going back to what we discussed before, i.e., to call the syntax fragments `IntAst` instead of just `Int`

I agree that this makes sense!

**Comment by david-broman** [comment]
@elegios OK, good.
@EliasC OK, good point with pattern syntax. I will keep `IntPat` for now.

**Comment by EliasC** [comment]
@david-broman @elegios: Has this issue been addressed? Can we close it?
