### ISSUE TITLE
Comparison of printing utf-8 encoded chars in OCaml vs MExpr in `generate.mc`

### ISSUE THREAD

**Issue by gizemcaylak** [miking-lang/miking#324]
In `generate.mc`, when I try to test if the compiler work as intended for unicode characters using `utest` with
`build/mi test stdlib/ocaml/generate.mc`, this case  
` utest ocamlEvalChar (char_ '島') with (char_ '島') using eqExpr in`
gives an MExpr parsing error:
`ERROR: Unknown character. Expected '''.`

`ocamlEvalChar` evaluates the OCaml program [`(char_ '島')`], takes the printed output and parses it with MExpr parser and then compare it with the right hand side of the utest [using python at the backend in `stdlib/ocaml/process-helpers.mc`]:
```
  let print_to_string = lam num. app_ ( app_ ( (OTmVarExt {ident = "Printf.printf"}) ) (OTmString {text="'%s'"}))
  (app_ (OTmVarExt {     ident = "Boot.Ustring.to_utf8"})
  (app_ (OTmVarExt {     ident = "Boot.Ustring.Op.array2ustring"})
  (app_ (OTmVarExt {     ident = "Array.make 1"}) num)
  ))
in
let ocamlEvalChar = lam ast.
   ocamlEval (wrapOCamlAstInPrint ast (ulam_ "x" (print_to_string (var_ "x"))))
```
`print_to_string` is very similar to `print_char` in `Boot.Ustring` module (only difference is single quotes surrounding the string). 
The generated OCaml program to print this unicode character is:
```
(fun var_x ->
((Printf.printf) ("'%s'")) ((Boot.Ustring.to_utf8) ((Boot.Ustring.Op.array2ustring) ((    Array.make 1) (var_x))))) (23798)
```
When this is executed separately, it gives the expected output '島'. However, with
`build/mi test stdlib/ocaml/generate.mc`, the output is 'å³¶'. I think **this is a problem related to python decode/encode stage in`stdlib/ocaml/process-helpers.mc`**. However, I couldn't solve it by trying different encoding/decoding schemes.

**Comment by larshum** [comment]
Interesting! Hopefully this will be fixed when we stop depending on the Python intrinsics.

PR #323 includes a workaround for the problem with `ocamlEvalChar`. By representing characters as integers, using `ocamlEvalInt` to evaluate and parse the result, and then reinterpreting the integer as a character, we don't need to worry about the encoding.
