### ISSUE TITLE
The function map traverses sequence in different order in boot and the compiler

### ISSUE THREAD

**Issue by br4sco** [miking-lang/miking#390]
The program 
```
-- test.mc
include "seq.mc"

mexpr
map print [" 1 ", " 2 "]
```
Reverses the order of the map function depending on whether it is evaluated or compiled. I.e.
```
boot eval test.mc
 1  2 
```
but on the other hand
```
mi compile test.mc && ./test
 2  1 
```

**Comment by lingmar** [comment]
This seems to be fixed, I'm guessing after #389 was merged. But perhaps the real problem remains somewhere else, even though it works for `map` right now.
