### ISSUE TITLE
Ordering of abstract syntax in MLang language fragments

### ISSUE THREAD

**Issue by br4sco** [miking-lang/miking#45]
At our last meeting we discussed a semantic function `<` in MLang that would define an ordering over the elements defined in the `syn` declaration. The problem is that an author of a language fragment cannot and should not assume anything about `syn` elements in other language fragments.

I suggest the following solution:

We include a constant, lets call it `ltsyn` (naming can surely be improved) that takes two `syn` elements and compares their labels. One way to implement `ltsyn` would be by using a lexiographical ordering (as pointed out by @dlunde), but I believe the exact implementation of `ltsyn` should remain hidden from the language fragment author. As an example, if we implement `ltsyn` using a lexicographical ordering;

`ltsyn (CInt i) (CFloat f)` would evaluate to `false` for all `i` and `f` 

I guess `ltsyn (CFloat f1) (CFloat f2)` should probably give an error for all `f1` and `f2`.

A language fragment author can then define a semantic function `lt` over the `syn` element in his/her own language fragment. For two language fragment for floats and ints this could look something like this:

```
lang Float
syn Const =
| CFloat Float

sem lt (other : Const) =
| CFloat f2 -> 
  match other with CFloat f1 then ltf f1 f2
  else ltsyn other (CFloat f2)
| _ -> error "comparison undefined"
end

lang Int
syn Const =
| CInt Int

sem lt (other : Const) =
| CInt i2 ->
  match other with CInt i1 then lti i1 i2
  else ltsyn other (CInt i2)
| _ -> error "comparison undefined"
end
``` 

Then, `lang FloatInt = Float + Int` have an ordering over all `syn` elements in the language via the semantic function `lt`.

Note, I guess the constant `ltsyn` must be parametrized over the `syn` type.

**Comment by EliasC** [comment]
Is the point of this to get a comparison function for your syntactic constructs for free? If so, the problem could be extended to (e.g.) equality, printing, [insert your favourite type class here]. Or is the purpose something different?

> I guess `ltsyn (CFloat f1) (CFloat f2)` should probably give an error for all `f1` and `f2`.

I would expect it to evaluate to `false`, like `5 < 5`, no?

**Comment by br4sco** [comment]
> I would expect it to evaluate to false, like 5 < 5, no?

Yes!

The preceding discussion concerned how we could create Maps (as in the datastructure) over syntactic constructs, hence we needed some ordering. We haven't really discussed this more since that meeting.
