### ISSUE TITLE
Implicit or explicit quantification in function type signatures

### ISSUE THREAD

**Issue by elegios** [miking-lang/miking#554]
When writing an explicit type signature for a polymorphic function we've previously assumed implicit quantification, e.g., a type signature `a -> a` actually means `all a. a -> a`. The typechecker in #553 does not do this however, instead `a -> a` would be an error since `a` is unbound. We need to decide on what behavior we want in mexpr. This issue tries to summarize the options available and the relevant arguments.

## Basic scoping, as things currently stand

Relevant information: `all` introduces type variables in a slightly odd scope, following the FreezeML spec. This example is fully explicit, no implicit quantification:

```
let f : all a. a -> a =
  let g
    : a -> a  -- `a` is in scope here, despite not being a descendant of the `all` that introduces it
    = lam x. x in
  g
```

## Scoping and implicit quantification

A relevant question is which types get implicitly quantified and how it interacts with scoping. This example assumes some form of implicit quantification:

```
let apply : (a -> b) -> a -> b = lam f. lam a.
  let inner : a -> b = f in
  inner a
```

`apply` is here clearly implicitly quantified, but it's not as obvious what happens with `inner`. We have two options:
- Implicit quantification behaves precisely as explicit quantification, thus `inner` is monomorphic, and this code typechecks.
- Implicit quantification does not put its typevariables in scope, thus `inner` is supposed to be polymorphic over `a` and `b`, whereby it does *not* typecheck, since `f` is not polymorphic. This is how Haskell does it. Notably this would typecheck if we removed the annotation from `inner`.

This effect (`inner` may not use `f` unless we remove the explicit type signature) also happens with typeclasses in Haskell. For example:

```haskell
foo :: Ord k => k -> v -> Map k v -> Map k v
foo k v m = inner k v m
  where
    inner :: k -> v -> Map k v -> Map k v
    inner = Map.insert
```

This code does not typecheck because we don't have an instance of `Ord k` inside `inner`, since it's a different `k` from the one in `foo`. The code can be fixed in two ways:
- Adding explicit `forall`s in the typesignature of `foo`
- Removing the typesignature for `inner`, in which case we infer the signature that uses "the same" `k` and `v`, even though we couldn't write that signature explicitly.

Of course, we don't have typeclasses in MExpr, so this is only tangetially related, but we might get similar constructs, whereby this would be relevant.

## Locality of the transformation

The basic description of implicit quantification is "add universal quantifiers for all unbound type variables". The "unbound" in this sentence implies that the transformation cannot be local. I *believe* that all currently available syntactic sugar is local, e.g., rewriting `"abc"` to `['a', 'b', 'c']`, or `match a with b in c` to `match a with b then c else never` requires no knowledge of surrounding code. This stands in contrast with implicit universal quantification, with which `let foo : (a -> b) -> [a] -> [b] = ...` can have any of these meanings, depending on its surroundings:
- `let foo : (a -> b) -> [a] -> [b]` (both are already bound)
- `let foo : all b. (a -> b) -> [a] -> [b]` (`a` is already bound)
- `let foo : all a. (a -> b) -> [a] -> [b]` (`b` is already bound)
- `let foo : all a. all b. (a -> b) -> [a] -> [b]` (neither is already bound)

## Compromise 1, error on nesting

Most of the concerns above are about the behavior when nesting these things. We could require explicit quantification only when this sort of nesting occurs, e.g.,
```
let f : a -> a =
  let g
    : a -> a
    = lam x. x in
  g
```
is not ok, we produce and error requiring adding `all`s to `f`. There are questions here on what we should actually detect though, e.g., should we error if the type annotation of `g` is `b -> b`? If not, that means that changing the name used (`a`) in `f`'s typesignature can change whether the function compiles, even though nothing inside the body actually uses that name, because type variable shadowing is now not allowed in this way.

I suspect that this might also have some interactions with code generation + pretty printing + parsing, where pretty-printing has to be cautious about how it prints explicit type signatures with polymorphism, to avoid triggering this error.

## Compromise 2, semi-implicit universal quantification

We could add a new form that is shorter than full explicit quantification but still somewhat explicit, e.g., `let map : all. (a -> b) -> [a] -> [b]`. This form could represent a local or non-local transformation, depending on what we want to prioritize:
- If we want to prioritize clarity of the connection between code and AST, i.e., we want the transformation to be local, then we quantify all type variables that appear in the type, regardless of whether they are bound in the enclosing scope or not. Examples:
  - `all. (a -> b) -> [a] -> [b]` is equivalent with `all a. all b. (a -> b) -> [a] -> [b]` (this is true even if `a` or `b` is already bound).
  - `all. (all x. x -> Option x) -> a -> Option a` is equivalent with `all a. (all x. x -> Option x) -> a -> Option a` (we only quantify free variables, `x` is not free).
  - `all. (all. x -> Option x) -> a -> Option a` is also equivalent with `all a. (all x. x -> Option x) -> a -> Option a` (we can put this semi-explicit quantifier anywhere in the type).
  - `all. (all. x -> Option a) -> a -> Option a` is equivalent with `all a. (all x. all a. x -> Option a) -> a -> Option a` (the inner `a` is shadowed, since it appears free under the `all.`).
- If we want to prioritize convenience in cases where only *some* type variable should be quantified then we could make this transformation aware of its enclosing scope, i.e., it's the "obvious" implicit universal quantification, but with an opt-in marker.

**Comment by elegios** [comment]
Personal opinion, to at least try to separate it from the issue itself: I would prefer either
- fully explicit quantification, or
- the opt-in marker that is fully local, i.e., it quantifies over all free (as opposed to unbound) type variables.

**Comment by aathn** [comment]
Personally I don't have a strong opinion on this. I feel like it would be in line with the rest of MCore's design to require explicit quantification, but it might be a bit cumbersome to write, and unfamiliar to people used to implicit quantification.

A simpler alternative to the opt-in marker mentioned above could be to offer a shorter syntax

    all a b c. T ~ all a. all b. all c. T

But this would be a bit inconsistent as we don't have that for `lam`...

**Comment by br4sco** [comment]
I prefer the fully explicit quantification. 
- It is the simplest solution and is not implicit in any way. I think it is a good thing to avoid introducing complexity when we do not know beforehand where we want to take this type-system. 
- It is analogue to how we treat function arguments (i.e. `lam x. ...`).

The two main arguments I've seen so far for implicit quantification are:
1. It is cumbersome to write, which might be true but so is writing `lam` all the time. Ease of writing should be less of an argument for a core language such as MCore. Especially when you have to think more than 2 second what this syntactic sugar means in the examples vipa discussed above. It is not as straight forward as lets say `"123"` means `['1','2','3']`.
2. We have used a lot of implicit quantification in the standard library already. Fixing this is a one-time thing. I do not think it is that much work and besides Anders has already done the work for `seq.mc`, `option.mc`, (and more?) in his PR.

I'm also not so fond of the `all.` syntax proposal as it is not really analogous to `lam.` which says we have an identifier that will never appear in the body of the lambda where `all.` says something different. If we want this approach I think we should use some other syntax. However, It also does not help with point 2 that much and I wonder of it is worth introducing a new language construct for this purpose.

**Comment by elegios** [comment]
We decided on fully explicit quantification.
