### ISSUE TITLE
Semantic functions matching on primitive data

### ISSUE THREAD

**Issue by EliasC** [miking-lang/miking#67]
As has been discussed for example in #25 and in the work on extensible parsers, there are occasions when it would make sense to allow semantic functions to match on primitive data in order to extend and compose language fragments which handle different data. The use case from #25 is in the context of an extensible string formatter, in condensed form here:
```
lang FmtBase
  syn Fmt =

  sem readFmt (fmt : Fmt) =
end

lang FmtInt = FmtBase
  syn Fmt =
  | FmtInt Int

  sem readInt
  | FmtInt n -> int2str n
  | _ -> error "Expected an integer"

  sem readFmt (fmt : Fmt) =
  | '%' :: 'd' :: s -> readInt fmt
end

lang FmtString = FmtBase
  syn Fmt =
  | FmtString String

  sem readString
  | FmtString s -> s
  | _ -> error "Expected a String"

  sem readFmt (fmt : Fmt) =
  | '%' :: 's' :: s -> readString fmt
end

lang MyFmt = FmtInt + FmtString
```
This example matches both on sequences (strings) and primitive data (characters), allowing fragments to add new format specifiers. At the moment, we might be able to work around this by translating a format string into a sequence of format specifier tokens (e.g. `"%s=%d"` -> `[SpecString, NoSpec '=', SpecInt]`), but this seems like quite a lot of overhead. The tricky part about getting this to work is detecting ambiguity, especially in cases that are more complicated than "map this sequence of characters to this concrete value" (for example C-style formatting, like `%.2d`). In particular, in such cases it would be natural to write guards (`c :: s when isDigit c`), which quickly becomes unfeasible to check for ambiguity statically.

This issue is an invitation to discuss this problems and its solutions.

**Comment by elegios** [comment]
It is worth mentioning that some of this stuff is in `mexpr` already, but not `mlang`; we can match on sequences with, e.g., `[pre, fix] ++ rest` and `rest + [post, fix]`, and we also allow nested patterns.

What is missing at present are guards, and also implementing nested patterns in `mlang`, since they have an impact on the merging semantics that we have not yet explored properly.
