### ISSUE TITLE
File namespace proposal

### ISSUE THREAD

**Issue by aathn** [miking-lang/miking#716]
To allow Miking code to refer to files outside of both the standard library and the current project, this proposal introduces a concept of *file namespaces*. This is a temporary solution, as we anticipate that a proper solution based on modules and packages or similar will require a more in-depth design discussion.

<a id="orgaf15e96"></a>

# Basic idea

File namespaces are simply names associated with directories, such as the following.

```bash
stdlib=/path/to/miking/stdlib
mypkg=/path/to/mypkg/src
```

We extend the `include` syntax to optionally accept a prefix of file namespace followed by a double colon (or some other delimiter, to be discussed).

```mcore
include "stdlib::error.mc"
include "mypkg::linear-time-travelling-salesman.mc"
```

In this case, the first include would resolve to the file `/path/to/miking/stdlib/error.mc`, and the second to `/path/to/mypkg/src/linear-time-travelling-salesman.mc`.

<a id="org9230320"></a>

# Specifying namespaces

We replace the `MCORE_STDLIB` environment variable with a ~`MCORE_LIBRARY_PATH`~ `MCORE_LIBS` variable containing the namespaces of installed libraries. This variable will be a colon-separated list of pairs `name=path` specifying the association between namespace and filesystem path.

For the example above, we would use the following.

```bash
export MCORE_LIBS="stdlib=/path/to/miking/stdlib:mypkg=/path/to/mypkg/src"
```

<a id="orgf21d2d5"></a>

# Why namespaces?

We could adopt an even simpler approach than the one above, where we simply expand `MCORE_STDLIB` to be a list of paths, and try each path in turn when resolving includes.

For instance, we could have `MCORE_STDLIB=/path/to/miking/stdlib:/path/to/mypkg/src` and then directly refer to the paths as follows.

```mcore
include "error.mc"
include "linear-time-travelling-salesman.mc"
```

However, we run into trouble if the same file, say `common.mc` occurs in both `stdlib` and `mypkg`. At this point, we would have no way of knowing which file was intended, and would either have to choose one arbitrarily or throw an error. Furthermore, this conflict cannot be easily resolved by the end user, as it requires changing the file structure of one of the packages (and packages cannot be expected to account for the possibility of other packages with the same file names).

Hence, we need some way for the user to differentiate between included files, and this is what namespaces give us.

<a id="org5d99fdd"></a>

# Special namespaces and local files

Always referring to namespaces explicitly may be tedious in some cases (and would require rewriting a lot of the existing code). For one, we would like to be able to refer to files in the standard library without explicitly naming `stdlib`. In addition, we might want to refer to files in relation to the project root (to avoid having to write paths like `../../common.mc`).

To account for this, I propose we use two special namespaces, `root` and `stdlib`, which are always implicitly available. [In the long run, this warrants more discussion, as it may be better to be explicit than ambiguous]

For instance, if I set `root=/path/to/mypkg/src` and `stdlib=/path/to/miking/stdlib`, I could write the following.

```mcore
include "error.mc"
include "linear-time-travelling-salesman.mc"
```

Then, the two includes would resolve to `/path/to/miking/stdlib/error.mc` and `/path/to/mypkg/src/linear-time-travelling-salesman.mc`, even from a subdirectory of `mypkg/src`.

In case the same file exists in more than one of {locally,project root,standard library}, the user would be required to disambiguate by writing the namespace, or prefixing the file name with `./` or `../` (and an error would be thrown otherwise).

```mcore
include "./error.mc"
include "root::error.mc"
include "stdlib::error.mc"
```

Supposing the user is in directory `/path/to/mypkg/src/subdir`, the three inclusions would resolve to `/path/to/mypkg/src/subdir/error.mc`, `/path/to/mypkg/src/error.mc` and `/path/to/miking/stdlib/error.mc`, respectively.

The `root` namespace would be treated specially, to ensure it always refers to the root of the namespace being handled. For instance, consider the following case, where we have four files `mypkgA/src/file{1,2}.mc`, `mypkgB/src/file{1,2}.mc`.

`mypkgA/src/file1.mc`

```mcore
include "mypkgB::file1.mc"
include "root::file2.mc"
```

`mypkgB/src/file1.mc`

```mcore
include "root::file2.mc"
```

Here, we would like `root::file2.mc` to resolve to `mypkgA/src/file2.mc` in the first file, but `mypkgB/src/file2.mc` in the second file. Hence, the inclusion parsing would need to update `root` to the value of `mypkgB` when passing through the inclusion of `mypkgB::file1.mc`.

The `root` namespace would be set through a separate variable `MCORE_ROOT` to make it easy to update on a per-folder basis using something like [direnv](https://direnv.net).

<a id="org0b7ca9f"></a>

# Problems with the approach

Although this approach avoids the most basic name clashes mentioned above, it still has some pretty serious limitations in terms of scaling.

Suppose we have the following scenario:

-   Package A depends on package C, referring to it as `pkg`.
-   Package B depends on package D, referring to it as `pkg`.
-   I want to depend on both package A and package B.

In this scenario, we are essentially out of luck, and need a more sophisticated approach. However, this name clash is on the level of *namespaces*, as opposed to *file names*, making it slightly less serious. As long as we are consistent about referring to every library with a unique name, and the ecosystem is small enough to make this reasonably easy, we should have no issues.

**Comment by johnwikman** [comment]
My initial thought is that this is probably too sophisticated for the immediate issue with includes, or do we have the case with two separate packages that we want to include?

Could it suffice to have the rule that we first try local path, then resort to the absolute path if necessary?
```
-- Include error from stdlib
include "std::error.mc"

-- Include error locally if it exists, otherwise use the one from stdlib
include "error.mc"

-- Local file only
include "./error.mc"
```

Seeing as it is a stop-gap solution for something else, I see a risk with making it too sophisticated when we start to integrate it into our code as it will probably be harder to get rid of in the future.

**Comment by aathn** [comment]
I mean, that's essentially what it would be except for the `root` thing.  (Note that the current implementation also errors in case a file exists both locally and in the standard library.)  Perhaps the root namespace is more sophisticated than we need at the moment.

**Comment by johnwikman** [comment]
I was more reacting to this `export MCORE_LIBRARY_PATH="stdlib=/path/to/miking/stdlib:mypkg=/path/to/mypkg/src"` being a temporary API that may prove troublesome to have backwards compatibility for when we decide to deprecate it. I think that this more sophisticated namespacing functionality would be nice to have in the long run, with the root reference and more. But I would see that as part of a bigger restructuring of the entire include system instead of a stop-gap solution.

**Comment by aathn** [comment]
> do we have the case with two separate packages that we want to include?

The issue motivating this proposal is that `treeppl` is getting separated to its own repo, and needs to depend on both `coreppl` and `stdlib`, which isn't currently possible.

**Comment by johnwikman** [comment]
Ah, that justifies it :slightly_smiling_face: Then I think that the overall interface looks good. The comments I have then is:

* We should probably have backwards compatibility for `MCORE_STDLIB`. Such that unless overwritten by the library path, have `stdlib::` being bound to the `MCORE_STDLIB` variable or whatever the default is.
* The `root::` functionality looks nice, but if it is not needed then I think that it should wait.
