### ISSUE TITLE
Bikeshedding: Comment syntax

### ISSUE THREAD

**Issue by EliasC** [miking-lang/miking#95]
Sometimes the least important decisions require the most discussion. With that in mind, let's talk syntax! We have had some informal discussions regarding the syntax for comments, and the point of this space is to continue the discussion in an archived fashion (and hopefully reach a conclusion). 

We currently support two kinds of line comments:
- Haskell-style: `-- This is a comment`
- C-style: `// This is a comment`

For starters, we should decide on a single style (which doesn't have to be one of these two). We should also decide on a syntax for block comments, and there should be a clear connection between the two. I remember three suggestions being brought up:

- A riff on the Haskell-style:
  ```
  -- This is a line comment
  --*
    This is a
    block comment
  *--
  ```
- A variation with identical open/close symbols:
  ```
  -- This is a line comment
  *--
    This is a
    block comment
  *--
  ```
- C-style all the way:
  ```
  // This is a line comment
  /*
    This is a
    block comment
  */
  ```

The floor is open, both for discussing these alternatives and for suggesting new ones!

**Comment by br4sco** [comment]
A variation on the first one would be:
```
-- This is a line comment
-*
  This is a
  block comment
*-
```

**Comment by EliasC** [comment]
@br4sco: Maybe that was even the original suggestion, come to think of it!

**Comment by johnwikman** [comment]
I like @br4sco's suggestion for block comments. I am not too demanding on the syntax here, but it would be good to have the ability to nest block comments.

Edit: Another thing to perhaps add to this discussion is documentation and if we would like to generate online reference manuals similar to how Doxygen does it:
```
-*
 * Sorts a sequence of elements using heap sort.
 *   lam lt: Performs the less-than operation (<) on elements in the input array.
 *   lam s:  The sequence to be sorted.
 *-
let heapsort = lam lt : (a -> a -> Bool). lam s : [a].
  ...
```

**Comment by david-broman** [comment]
I think I prefer Oscar's suggestion, or the one with two dashes
```
--*
text 
*--
```
I agree with John, it is important to support nested block comments.

**Comment by br4sco** [comment]
I don't know if there are parsing considerations to this but how about using a markdown code block style block comment?

A variation on the first one would be:
```
-- This is a line comment
---
  This is a
  block comment
---
```

I guess you can increase the number of `-` to better distinguish the block comment from the line comment if you wish.

**Comment by segeljakt** [comment]
You wont be able to meta-program the comments?!? 😆

**Comment by EliasC** [comment]
A summary of the discussion of today's Zoom meeting:
- This is Haskell's syntax:
  ```
  {-
  Block comment
  -}
  ```
  It's unfortunate that editors with matching of delimiters will 
  get confused about the extra open `}`
- These comments look like swords:
  ```
  *\
  * This is a block comment
  * with more than one line
  */
  ```
  
  ```
  */
  * This is a block comment
  * with more than one line
  *\
  ```
  
  In both these examples, only the asterixes of the of first
  and final lines are mandatory, but the other ones align
  nicely. It is weird that this is C style syntax with a
  flipped slash for one of the delimiters and flipped order
  for the opening delimeter.
- For the Haskell riffing block-comments we have two versions:
  ```
  --*
    * This is a block comment
    * with more than one line
  *--
  ```
  ```
  *--
  * This is a block comment
  * with more than one line
  --*
  ```
  
  The latter arguably has better potential for aligning stars.
  It departs from the de-facto standard of having the star on
  the "inside" of the delimiters. The former could also have
  aligned dashes:
  ```
  --*
  -- This is a block comment
  -- with more than one line
  *--
  ```
  
  Unfortunately we cannot hack either of these three versions
  by writing e.g.
  ```
  --*
  -- This is a block comment
  -- with more than one line
  --*--
  ```
  as the last line will be parsed as an opening of a new block comment

**Comment by dlunde** [comment]
Very nice writeup Elias!

**Comment by johnwikman** [comment]
I have spent a bit of time recently thinking about block comments, and have come up with a set of criteria for what I want from a block comment:
 1. The symbols involved in the opening and closing terms should be familiar characters that can be easily accesible without need for the Alt Gr modifier or keypress+space (e.g. `~`) on the keyboard.
 2. Preferrably a maximum of 2 symbols in the opening and closing terms of the block comment.
 3. The closing term should feel like the inverse of the opening term. After seeing the opening term, it should be easy to guess the closing term.
 4. The block comment should look good both on a single line and when spanning multiple lines.
 5. When spanning multiple lines, there should be a nice way of structuring the block comment such that it feels like that the block comment "encapsulates" its contents.
 6. The block comment should work as a function documentation suitable for autogenerated web pages, like doxygen.
 7. A block comment should try to resemble the single line comment, they should not look alien positioned next to each other.

The only syntax that I have come up with so far (that I feel meets most of my criteria) is to use `*-` for opening a block comment and `-*` for closing a block comment. Some examples:
```
 *-
 * This is a
 * block comment
-*
let foo = mapi addi

*- Inline comment -*
-- Regular comment

 *-
 * .brief This works as function documentation fairly well.
 *
 * .lam[x] The input array
 *
 * .return The map results
-*
let foo: [Int] -> [Int] =
  lam x.
  mapi addi x

 *-
  But maybe not as well as a
  standalone block comment
-*
```

**Comment by david-broman** [comment]
I support John's argumentation. Looking back to what we discussed earlier at the Zoom meeting, and Elias's summary, I also prefer `*-  text -*` for multiline comments, and just stick to `--` for one line comments. That is, remove the support for `//`.

**Comment by dlunde** [comment]
Works for me

**Comment by EliasC** [comment]
I also agree with @johnwikman's reasoning. The fact that
```
 *-
This is a block comment
-*
```

Doesn't look as good as
```
 *-
 * This is a block comment
-*
```
suggests to me that the latter should probably be the prescribed style (but not be mandatory, since we also use commenting for disabling code). I could also see the following work to avoid having to indent the opening delimiter:
```
*-
* This is a block comment
* which is not indented
------------------------*

**Comment by david-broman** [comment]
We decided to go with `*-  -*`  and `--`
Note that `*- -*` should be nested.

**Comment by dlunde** [comment]
I think you meant `*- -*` and `--`!

**Comment by david-broman** [comment]
Forgot to escape the code :-)
